### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by bsamadi** [mlakhia/mapify.io#2]
I can't enable the Mapify Kijiji extension.

**Comment by mlakhia** [comment]
Hi @bsamadi I received a few comments that it was no longer functional. Due to a lack of time and interest I haven't made time to improve or maintain it, so I've disabled it in the Chrome Web Store -- which might explain why you are no longer able to enable it. Apologies for the inconvenience.

**Comment by bsamadi** [comment]
@mlakhia Kijiji is driving me crazy. I wish they would have supported you.
